// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oksvnedwfhgisevnotax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rc3ZuZWR3ZmhnaXNldm5vdGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzQ3OTIsImV4cCI6MjA2MTUxMDc5Mn0.e30QqNUjjd3l527Pgr6UBvwn6lgtoIMlIA0qfN1a1nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);